#!/bin/sh
# Writes Config/Generated/GoogleSecrets.xcconfig from local Secrets.plist / env.
# Also bakes GIT_SHA / GIT_BRANCH from `git -C "$SRCROOT"` when that tree is a
# repo — never invents a SHA. Empty SHA becomes "unknown SHA" on SHA-asks.
# Used as a scheme Pre-action and as an Xcode Run Script whose ONLY output
# is that xcconfig — never the built app Info.plist.
# Config/VoiceDesk.xcconfig #include?s the file so $(GOOGLE_*) and $(GIT_*) substitute.
# DEVELOPMENT_TEAM is optional: written only when Secrets.plist / env has one.
# Missing team is not an error — Xcode Signing UI can supply it for device runs.
# Never prints secret values. Never writes DEVELOPMENT_TEAM unless Secrets/env has one.
# Manual: ./scripts/inject-google-secrets.sh

set -eu

SRCROOT="${SRCROOT:-$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)}"
SECRETS="${SRCROOT}/VoiceDesk/Secrets.plist"
GENERATED_DIR="${SRCROOT}/Config/Generated"
XCCONFIG="${GENERATED_DIR}/GoogleSecrets.xcconfig"

plist_get() {
    # $1 = file, $2 = key
    if [ ! -f "$1" ]; then
        return 0
    fi
    if [ -x /usr/libexec/PlistBuddy ]; then
        /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || true
        return 0
    fi
    if command -v python3 >/dev/null 2>&1; then
        python3 -c '
import plistlib, sys
with open(sys.argv[1], "rb") as handle:
    data = plistlib.load(handle)
value = data.get(sys.argv[2], "")
print("" if value is None else value)
' "$1" "$2" 2>/dev/null || true
        return 0
    fi
    # Linux CI (swift:6.0) has neither PlistBuddy nor python3.
    awk -v key="$2" '
        index($0, "<key>" key "</key>") {
            if (getline <= 0) exit
            sub(/^[[:space:]]*<string>/, "")
            sub(/<\/string>[[:space:]]*$/, "")
            print
            exit
        }
    ' "$1" 2>/dev/null || true
}

trim() {
    printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

sanitize_team() {
    # Apple Team IDs are 10 alphanumeric characters. Drop anything else
    # so a dirty plist cannot break the xcconfig.
    printf '%s' "$1" | tr -cd 'A-Za-z0-9'
}

is_placeholder() {
    value="$(trim "${1:-}")"
    case "$value" in
        ""|"com.googleusercontent.apps.REPLACE_ME"|*REPLACE_ME*|'$(GOOGLE_REVERSED_CLIENT_ID)'|'$(GOOGLE_CLIENT_ID)'|'$(DEVELOPMENT_TEAM)')
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

derive_reversed() {
    client="$(trim "$1")"
    suffix=".apps.googleusercontent.com"
    case "$client" in
        *"$suffix")
            prefix="${client%"$suffix"}"
            if [ -n "$prefix" ]; then
                printf '%s' "com.googleusercontent.apps.${prefix}"
            fi
            ;;
    esac
}

CLIENT="$(trim "$(plist_get "$SECRETS" GOOGLE_CLIENT_ID)")"
REVERSED="$(trim "$(plist_get "$SECRETS" GOOGLE_REVERSED_CLIENT_ID)")"
TEAM="$(sanitize_team "$(trim "$(plist_get "$SECRETS" DEVELOPMENT_TEAM)")")"

if ! is_placeholder "${GOOGLE_CLIENT_ID:-}"; then
    CLIENT="$(trim "$GOOGLE_CLIENT_ID")"
fi
if ! is_placeholder "${GOOGLE_REVERSED_CLIENT_ID:-}"; then
    REVERSED="$(trim "$GOOGLE_REVERSED_CLIENT_ID")"
fi
if ! is_placeholder "${DEVELOPMENT_TEAM:-}"; then
    TEAM="$(sanitize_team "$(trim "$DEVELOPMENT_TEAM")")"
fi

if is_placeholder "$REVERSED"; then
    REVERSED="$(derive_reversed "$CLIENT")"
fi

git_identity_lines() {
    sha=""
    branch=""
    if command -v git >/dev/null 2>&1 \
        && git -C "$SRCROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        raw="$(trim "$(git -C "$SRCROOT" rev-parse --short=7 HEAD 2>/dev/null || true)")"
        case "$raw" in
            *[!0-9a-fA-F]*|"")
                ;;
            *)
                if [ "${#raw}" -ge 4 ] && [ "${#raw}" -le 12 ]; then
                    sha="$(printf '%s' "$raw" | tr 'A-F' 'a-f')"
                fi
                ;;
        esac
        br="$(trim "$(git -C "$SRCROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)")"
        if [ -n "$br" ] && [ "$br" != "HEAD" ]; then
            branch="$(printf '%s' "$br" | tr -cd 'A-Za-z0-9._/-')"
        fi
    fi
    if [ -n "$sha" ]; then
        echo "GIT_SHA = ${sha}"
    else
        echo "GIT_SHA ="
    fi
    if [ -n "$branch" ]; then
        echo "GIT_BRANCH = ${branch}"
    else
        echo "GIT_BRANCH ="
    fi
}

mkdir -p "$GENERATED_DIR"
if ! is_placeholder "$CLIENT"; then
    {
        echo "// Generated by scripts/inject-google-secrets.sh from local Secrets.plist — do not commit."
        echo "GOOGLE_CLIENT_ID = ${CLIENT}"
        if ! is_placeholder "$REVERSED"; then
            echo "GOOGLE_REVERSED_CLIENT_ID = ${REVERSED}"
        else
            echo "GOOGLE_REVERSED_CLIENT_ID ="
        fi
        if [ -n "$TEAM" ]; then
            echo "DEVELOPMENT_TEAM = ${TEAM}"
        fi
        git_identity_lines
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: wrote Config/Generated/GoogleSecrets.xcconfig from Secrets.plist"
else
    {
        echo "// Generated by scripts/inject-google-secrets.sh from local Secrets.plist — Secrets.plist has no GOOGLE_CLIENT_ID."
        echo "GOOGLE_CLIENT_ID ="
        echo "GOOGLE_REVERSED_CLIENT_ID ="
        if [ -n "$TEAM" ]; then
            echo "DEVELOPMENT_TEAM = ${TEAM}"
        fi
        git_identity_lines
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: no GOOGLE_CLIENT_ID in Secrets.plist; leaving Google keys empty"
fi
