#!/bin/sh
# Writes Config/Generated/GoogleSecrets.xcconfig from Secrets.plist / env.
# Used as a scheme Pre-action and as an Xcode Run Script whose ONLY output
# is that xcconfig — never INFOPLIST_PATH, never the built app Info.plist.
# Config/VoiceDesk.xcconfig #include?s the file so $(GOOGLE_*) substitute
# into Config/Info.plist. Derives the reversed client ID when missing.
# Never prints secret values.
# Manual: ./scripts/inject-google-secrets.sh

set -eu

SRCROOT="${SRCROOT:-$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)}"
SECRETS="${SRCROOT}/VoiceDesk/Secrets.plist"
GENERATED_DIR="${SRCROOT}/Config/Generated"
XCCONFIG="${GENERATED_DIR}/GoogleSecrets.xcconfig"

plist_get() {
    # $1 = file, $2 = key
    if [ ! -f "$1" ]; then
        return 0
    fi
    if [ -x /usr/libexec/PlistBuddy ]; then
        /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || true
        return 0
    fi
    if command -v python3 >/dev/null 2>&1; then
        python3 -c '
import plistlib, sys
with open(sys.argv[1], "rb") as handle:
    data = plistlib.load(handle)
value = data.get(sys.argv[2], "")
print("" if value is None else value)
' "$1" "$2" 2>/dev/null || true
    fi
}

trim() {
    printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

is_placeholder() {
    value="$(trim "${1:-}")"
    case "$value" in
        ""|"com.googleusercontent.apps.REPLACE_ME"|*REPLACE_ME*|'$(GOOGLE_REVERSED_CLIENT_ID)'|'$(GOOGLE_CLIENT_ID)')
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

derive_reversed() {
    client="$(trim "$1")"
    suffix=".apps.googleusercontent.com"
    case "$client" in
        *"$suffix")
            prefix="${client%"$suffix"}"
            if [ -n "$prefix" ]; then
                printf '%s' "com.googleusercontent.apps.${prefix}"
            fi
            ;;
    esac
}

CLIENT="$(trim "$(plist_get "$SECRETS" GOOGLE_CLIENT_ID)")"
REVERSED="$(trim "$(plist_get "$SECRETS" GOOGLE_REVERSED_CLIENT_ID)")"

if ! is_placeholder "${GOOGLE_CLIENT_ID:-}"; then
    CLIENT="$(trim "$GOOGLE_CLIENT_ID")"
fi
if ! is_placeholder "${GOOGLE_REVERSED_CLIENT_ID:-}"; then
    REVERSED="$(trim "$GOOGLE_REVERSED_CLIENT_ID")"
fi

if is_placeholder "$REVERSED"; then
    REVERSED="$(derive_reversed "$CLIENT")"
fi

mkdir -p "$GENERATED_DIR"
if ! is_placeholder "$CLIENT"; then
    {
        echo "// Generated by scripts/inject-google-secrets.sh — do not commit."
        echo "GOOGLE_CLIENT_ID = ${CLIENT}"
        if ! is_placeholder "$REVERSED"; then
            echo "GOOGLE_REVERSED_CLIENT_ID = ${REVERSED}"
        else
            echo "GOOGLE_REVERSED_CLIENT_ID ="
        fi
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: wrote Config/Generated/GoogleSecrets.xcconfig from Secrets.plist"
else
    {
        echo "// Generated by scripts/inject-google-secrets.sh — Secrets.plist has no GOOGLE_CLIENT_ID."
        echo "GOOGLE_CLIENT_ID ="
        echo "GOOGLE_REVERSED_CLIENT_ID ="
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: no GOOGLE_CLIENT_ID in Secrets.plist; leaving empty"
fi
