#!/bin/sh
# Reads gitignored VoiceDesk/Secrets.plist (if present) and writes
# GOOGLE_CLIENT_ID / GOOGLE_REVERSED_CLIENT_ID into:
#   1) Config/Generated/GoogleSecrets.xcconfig (next Xcode evaluation)
#   2) the already-processed app Info.plist (this build)
# Derives the reversed client ID when it is empty or REPLACE_ME.
# Never prints secret values.

set -eu

SRCROOT="${SRCROOT:-$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)}"
SECRETS="${SRCROOT}/VoiceDesk/Secrets.plist"
GENERATED_DIR="${SRCROOT}/Config/Generated"
XCCONFIG="${GENERATED_DIR}/GoogleSecrets.xcconfig"
INFO_PLIST="${TARGET_BUILD_DIR:-}/${INFOPLIST_PATH:-}"

plist_get() {
    # $1 = file, $2 = key
    if [ ! -f "$1" ]; then
        return 0
    fi
    /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || true
}

trim() {
    printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

is_placeholder() {
    value="$(trim "${1:-}")"
    case "$value" in
        ""|"com.googleusercontent.apps.REPLACE_ME"|*REPLACE_ME*|'$(GOOGLE_REVERSED_CLIENT_ID)'|'$(GOOGLE_CLIENT_ID)')
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

derive_reversed() {
    client="$(trim "$1")"
    suffix=".apps.googleusercontent.com"
    case "$client" in
        *"$suffix")
            prefix="${client%"$suffix"}"
            if [ -n "$prefix" ]; then
                printf '%s' "com.googleusercontent.apps.${prefix}"
            fi
            ;;
    esac
}

CLIENT="$(trim "$(plist_get "$SECRETS" GOOGLE_CLIENT_ID)")"
REVERSED="$(trim "$(plist_get "$SECRETS" GOOGLE_REVERSED_CLIENT_ID)")"

if ! is_placeholder "${GOOGLE_CLIENT_ID:-}"; then
    CLIENT="$(trim "$GOOGLE_CLIENT_ID")"
fi
if ! is_placeholder "${GOOGLE_REVERSED_CLIENT_ID:-}"; then
    REVERSED="$(trim "$GOOGLE_REVERSED_CLIENT_ID")"
fi

if is_placeholder "$REVERSED"; then
    REVERSED="$(derive_reversed "$CLIENT")"
fi

mkdir -p "$GENERATED_DIR"
if ! is_placeholder "$CLIENT"; then
    {
        echo "// Generated by scripts/inject-google-secrets.sh — do not commit."
        echo "GOOGLE_CLIENT_ID = ${CLIENT}"
        if ! is_placeholder "$REVERSED"; then
            echo "GOOGLE_REVERSED_CLIENT_ID = ${REVERSED}"
        fi
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: wrote Config/Generated/GoogleSecrets.xcconfig from Secrets.plist"
else
    {
        echo "// Generated by scripts/inject-google-secrets.sh — Secrets.plist has no GOOGLE_CLIENT_ID."
        echo "GOOGLE_CLIENT_ID ="
        echo "GOOGLE_REVERSED_CLIENT_ID ="
    } > "$XCCONFIG"
    echo "note: inject-google-secrets: no GOOGLE_CLIENT_ID in Secrets.plist; leaving empty"
fi

if [ -z "$INFO_PLIST" ] || [ ! -f "$INFO_PLIST" ]; then
    echo "note: inject-google-secrets: built Info.plist not present yet; xcconfig written"
    exit 0
fi

if is_placeholder "$CLIENT"; then
    exit 0
fi

if /usr/libexec/PlistBuddy -c "Print :GIDClientID" "$INFO_PLIST" >/dev/null 2>&1; then
    /usr/libexec/PlistBuddy -c "Set :GIDClientID ${CLIENT}" "$INFO_PLIST"
else
    /usr/libexec/PlistBuddy -c "Add :GIDClientID string ${CLIENT}" "$INFO_PLIST"
fi

if ! is_placeholder "$REVERSED"; then
    if /usr/libexec/PlistBuddy -c "Print :CFBundleURLTypes:0:CFBundleURLSchemes:0" "$INFO_PLIST" >/dev/null 2>&1; then
        /usr/libexec/PlistBuddy -c "Set :CFBundleURLTypes:0:CFBundleURLSchemes:0 ${REVERSED}" "$INFO_PLIST"
    else
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes array" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0 dict" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLName string app.voicedesk.google" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleTypeRole string Editor" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string ${REVERSED}" "$INFO_PLIST" 2>/dev/null || true
        /usr/libexec/PlistBuddy -c "Set :CFBundleURLTypes:0:CFBundleURLSchemes:0 ${REVERSED}" "$INFO_PLIST" 2>/dev/null || true
    fi
    echo "note: inject-google-secrets: patched built Info.plist GIDClientID + Google URL scheme"
else
    echo "note: inject-google-secrets: could not derive reversed client ID; leaving URL scheme unchanged"
fi
